site_name: Jasmine's Docs
site_url: https://jasmine333333.github.io/
theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.png
  favicon: img/favicon.ico